version: "3.5"
services:
  mqtt:
    image: eclipse-mosquitto
    hostname: mqtt
    container_name: mqtt
    expose:
      - "1883"
      - "9001"
    ports:
      - "7905:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf